### ISSUE TITLE
Algorithm problem when data is poisson

### ISSUE THREAD

**Issue by nloliveira** [glmgen/glmgen#28]
When `family = "poisson"`, the predicted values of the trendfilter object are unstable, assuming 1, 0, and Inf randomly. Running the same piece of code multiple times with the same seed produces different results. 

@ryantibs and I believe the problem is in the proximal Newton wrapper, since the issue is not observed when `family = "gaussian"`. 

Here's a reprex. You might need to run it a few times to observe the problem. 

```
library(glmgen)

set.seed(201)
ss <- 500
y_original <- rnorm(ss,0,1)

lambda <- exp(seq(log(30), log(0.001), length.out = 50))

breaks = seq(min(y_original), max(y_original), length.out = 100)
temp_hist <- hist(y_original, breaks = breaks)
y <- temp_hist$counts
X <- temp_hist$mids
n <- length(y)

set.seed(201)
mod <- trendfilter(x = X, y = y, k = 2, family = "poisson", lambda = lambda)
out <- predict(mod, lambda = lambda, type = "response")
out
```

**Comment by veeranjaneyulus** [comment]
@nloliveira I could reproduce the issue.

**Comment by veeranjaneyulus** [comment]
@nloliveira I could reproduce the issue.

**Comment by nloliveira** [comment]
@veeranjaneyulus thanks for looking into this! Unfortunately the problem still happens :/

**Comment by veeranjaneyulus** [comment]
You are right. There is a problem with warm starting. It seems to be working fine on your script after disabling warm starting. Please check again. Thanks.

**Comment by nloliveira** [comment]
It works now, thank you so much!

**Comment by veeranjaneyulus** [comment]
Thanks for checking!

**Comment by nloliveira** [comment]
@veeranjaneyulus although the code was working with the last fix, when I used it inside a simulation that ran the models multiple times, the problem happened again. I guess it's just happening less often, and that's why I didn't observe it in the reprex.
